# Model parameters
sarima_order: [ 1, 1, 1 ]
seasonal_order: [ 1, 1, 1, 12 ]

# Training parameters
train_size: 0.8

# Paths
data_path: "Emikovalid_retail_data.csv"
#static_database: "GHvalid_retail_data.csv"
static_database: "Emikovalid_retail_data.csv"
model_save_path: "models/"
plots_save_path: "plots/"

# Price Stragey value
minimum_margin: 3.0  # unit = %
desired_margin: 10.0 # unit = %
check_period: 7 # unit = days
turnover_high: 18 # 18 < is high
turnover_low: 2 # 2 >  is low
marketing_campaign: 1.0 # 

# margin steps
margin_default_step: 0.5 # 0.5 % up or down

# margin steps per Product_General_Category


# Price limits
max_price: 1000000.0
min_price: 0.01

# Category-specific margins (%)
category_margins:
  Electronics: 15
  Grocery: 5
  Clothing: 20
  Beverages: 5
  Home_Kitchen: 15
  Health_Beauty: 20

# Logging
log_level: "INFO"